[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numReplicas = 1

[mount]
source = "/data"
destination = "/data"</content>